export const chatFiles = [
  {
    ...require("./nine_en/likabilityNINE_C_common_Gotanda_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Hyakuichitaro_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Jio_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Kazuki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Koishi_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Miu_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Oi_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Q_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Todoroki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Tsuki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Tsuruko_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_common_Yo_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_Main1_Gotanda_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_Main1_Saigo_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_Main1_Tsuki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_C_Main4_Jio_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Enoki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Gotanda_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Hyakuichitaro_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Jio_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Kazuki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Koishi_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Miu_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Oi_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Q_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Saigo_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Todoroki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Tsuki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Tsuruko_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_common_Yo_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Begin_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Enoki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Gotanda_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Hyakuichitaro_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Jio_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Kazuki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Koishi_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Miu_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Oi_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Q_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Saigo_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Todoroki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Tsuki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Tsuruko_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main1_Yo_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Enoki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Gotanda_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Hyakuichitaro_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Kazuki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Koishi_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Miu_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Oi_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Q_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Saigo_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Todoroki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Tsuki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Tsuruko_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main2_Yo_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main3_Enoki_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main3_Saigo_en.json"),
  },
  {
    ...require("./nine_en/likabilityNINE_Main4_Miu_en.json"),
  },
];
